package bean;
// Generated 26/09/2025 08:58:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VarBolsas generated by hbm2java
 */
@Entity
@Table(name="var_bolsas"
    ,catalog="db_victoria_ruback"
)
public class VarBolsas  implements java.io.Serializable {


     private int varIdBolsas;
     private String varNome;
     private String varCategoria;
     private String varColoracao;
     private String varDescricao;
     private Double varPreco;
     private String varAtivo;
     private String varColecao;
     private String varTipo;
   

    public VarBolsas() {
    }

	
    public VarBolsas(int varIdBolsas) {
        this.varIdBolsas = varIdBolsas;
    }
    public VarBolsas(int varIdBolsas, String varNome, String varCategoria, String varColoracao, String varDescricao, Double varPreco, String varAtivo, String varColecao, String varTipo) {
       this.varIdBolsas = varIdBolsas;
       this.varNome = varNome;
       this.varCategoria = varCategoria;
       this.varColoracao = varColoracao;
       this.varDescricao = varDescricao;
       this.varPreco = varPreco;
       this.varAtivo = varAtivo;
       this.varColecao = varColecao;
       this.varTipo = varTipo;
      
    }
   
     @Id 

    
    @Column(name="var_id_bolsas", unique=true, nullable=false)
    public int getVarIdBolsas() {
        return this.varIdBolsas;
    }
    
    public void setVarIdBolsas(int varIdBolsas) {
        this.varIdBolsas = varIdBolsas;
    }

    
    @Column(name="var_nome", length=100)
    public String getVarNome() {
        return this.varNome;
    }
    
    public void setVarNome(String varNome) {
        this.varNome = varNome;
    }

    
    @Column(name="var_categoria", length=50)
    public String getVarCategoria() {
        return this.varCategoria;
    }
    
    public void setVarCategoria(String varCategoria) {
        this.varCategoria = varCategoria;
    }

    
    @Column(name="var_coloracao", length=50)
    public String getVarColoracao() {
        return this.varColoracao;
    }
    
    public void setVarColoracao(String varColoracao) {
        this.varColoracao = varColoracao;
    }

    
    @Column(name="var_descricao")
    public String getVarDescricao() {
        return this.varDescricao;
    }
    
    public void setVarDescricao(String varDescricao) {
        this.varDescricao = varDescricao;
    }

    
    @Column(name="var_preco", precision=22, scale=0)
    public Double getVarPreco() {
        return this.varPreco;
    }
    
    public void setVarPreco(Double varPreco) {
        this.varPreco = varPreco;
    }

    
    @Column(name="var_ativo", length=1)
    public String getVarAtivo() {
        return this.varAtivo;
    }
    
    public void setVarAtivo(String varAtivo) {
        this.varAtivo = varAtivo;
    }

    
    @Column(name="var_colecao", length=50)
    public String getVarColecao() {
        return this.varColecao;
    }
    
    public void setVarColecao(String varColecao) {
        this.varColecao = varColecao;
    }

    
    @Column(name="var_tipo", length=45)
    public String getVarTipo() {
        return this.varTipo;
    }
    
    public void setVarTipo(String varTipo) {
        this.varTipo = varTipo;
    }
     @Override
    public boolean equals(Object object) {
        if (object instanceof VarBolsas) {
            if (this.getVarIdBolsas()== ((VarBolsas) object).getVarIdBolsas()) {
                return true;
            }
        }

        return false;
    }



    


}


