package bean;
// Generated 26/09/2025 08:58:21 by Hibernate Tools 4.3.1


import dao.ClientesDAO;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VarClientes generated by hbm2java
 */
@Entity
@Table(name="var_clientes"
    ,catalog="db_victoria_ruback"
)
public class VarClientes  implements java.io.Serializable {


     private int varIdCliente;
     private String varNome;
     private String varCpf;
     private String varRg;
     private String varSexo;
     private Date varDataNascimento;
     private String varEmail;
     private String varEndereco;
     private String varTelefone;
     private String varCelular;
     private Date varDataCadastro;
     private String varAtivo;
     private Date varDataUltimaCompra;
     private BigDecimal varLimiteCredito;
     private String varEstadocivil;
     

    public VarClientes() {
    }

	
    public VarClientes(int varIdCliente) {
        this.varIdCliente = varIdCliente;
    }
    public VarClientes(int varIdCliente, String varNome, String varCpf, String varRg, String varSexo, Date varDataNascimento, String varEmail, String varEndereco, String varTelefone, String varCelular, Date varDataCadastro, String varAtivo, Date varDataUltimaCompra, BigDecimal varLimiteCredito, String varEstadocivil) {
       this.varIdCliente = varIdCliente;
       this.varNome = varNome;
       this.varCpf = varCpf;
       this.varRg = varRg;
       this.varSexo = varSexo;
       this.varDataNascimento = varDataNascimento;
       this.varEmail = varEmail;
       this.varEndereco = varEndereco;
       this.varTelefone = varTelefone;
       this.varCelular = varCelular;
       this.varDataCadastro = varDataCadastro;
       this.varAtivo = varAtivo;
       this.varDataUltimaCompra = varDataUltimaCompra;
       this.varLimiteCredito = varLimiteCredito;
       this.varEstadocivil = varEstadocivil;
      
    }
   
     @Id 

    
    @Column(name="var_IdCliente", unique=true, nullable=false)
    public int getVarIdCliente() {
        return this.varIdCliente;
    }
    
    public void setVarIdCliente(int varIdCliente) {
        this.varIdCliente = varIdCliente;
    }

    
    @Column(name="var_nome", length=100)
    public String getVarNome() {
        return this.varNome;
    }
    
    public void setVarNome(String varNome) {
        this.varNome = varNome;
    }

    
    @Column(name="var_cpf", length=11)
    public String getVarCpf() {
        return this.varCpf;
    }
    
    public void setVarCpf(String varCpf) {
        this.varCpf = varCpf;
    }

    
    @Column(name="var_rg", length=10)
    public String getVarRg() {
        return this.varRg;
    }
    
    public void setVarRg(String varRg) {
        this.varRg = varRg;
    }

    
    @Column(name="var_sexo", length=10)
    public String getVarSexo() {
        return this.varSexo;
    }
    
    public void setVarSexo(String varSexo) {
        this.varSexo = varSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="var_dataNascimento", length=10)
    public Date getVarDataNascimento() {
        return this.varDataNascimento;
    }
    
    public void setVarDataNascimento(Date varDataNascimento) {
        this.varDataNascimento = varDataNascimento;
    }

    
    @Column(name="var_email", length=60)
    public String getVarEmail() {
        return this.varEmail;
    }
    
    public void setVarEmail(String varEmail) {
        this.varEmail = varEmail;
    }

    
    @Column(name="var_endereco", length=150)
    public String getVarEndereco() {
        return this.varEndereco;
    }
    
    public void setVarEndereco(String varEndereco) {
        this.varEndereco = varEndereco;
    }

    
    @Column(name="var_telefone", length=15)
    public String getVarTelefone() {
        return this.varTelefone;
    }
    
    public void setVarTelefone(String varTelefone) {
        this.varTelefone = varTelefone;
    }

    
    @Column(name="var_celular", length=15)
    public String getVarCelular() {
        return this.varCelular;
    }
    
    public void setVarCelular(String varCelular) {
        this.varCelular = varCelular;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="var_dataCadastro", length=10)
    public Date getVarDataCadastro() {
        return this.varDataCadastro;
    }
    
    public void setVarDataCadastro(Date varDataCadastro) {
        this.varDataCadastro = varDataCadastro;
    }

    
    @Column(name="var_ativo", length=1)
    public String getVarAtivo() {
        return this.varAtivo;
    }
    
    public void setVarAtivo(String varAtivo) {
        this.varAtivo = varAtivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="var_dataUltimaCompra", length=10)
    public Date getVarDataUltimaCompra() {
        return this.varDataUltimaCompra;
    }
    
    public void setVarDataUltimaCompra(Date varDataUltimaCompra) {
        this.varDataUltimaCompra = varDataUltimaCompra;
    }

    
    @Column(name="var_limiteCredito", precision=10)
    public BigDecimal getVarLimiteCredito() {
        return this.varLimiteCredito;
    }
    
    public void setVarLimiteCredito(BigDecimal varLimiteCredito) {
        this.varLimiteCredito = varLimiteCredito;
    }

    
    @Column(name="var_estadocivil", length=11)
    public String getVarEstadocivil() {
        return this.varEstadocivil;
    }
    
    public void setVarEstadocivil(String varEstadocivil) {
        this.varEstadocivil = varEstadocivil;
    }


 @Override
    public boolean equals(Object object) {
        if (object instanceof VarClientes) {
            VarClientes clientes = (VarClientes) object;
            if (this.getVarIdCliente()== clientes.getVarIdCliente()) {
                return true;
            }
        }
        return false;

    }



}


