package bean;
// Generated 26/09/2025 08:58:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VarUsuarios generated by hbm2java
 */
@Entity
@Table(name="var_usuarios"
    ,catalog="db_victoria_ruback"
)
public class VarUsuarios  implements java.io.Serializable {


     private int varIdusuarios;
     private String varNome;
     private String varApelido;
     private String varCpf;
     private Date varDatanascimento;
     private String varSenha;
     private Integer varNivel;
     private String varAtivo;
     private Set varVendases = new HashSet(0);

    public VarUsuarios() {
    }

	
    public VarUsuarios(int varIdusuarios) {
        this.varIdusuarios = varIdusuarios;
    }
    public VarUsuarios(int varIdusuarios, String varNome, String varApelido, String varCpf, Date varDatanascimento, String varSenha, Integer varNivel, String varAtivo, Set varVendases) {
       this.varIdusuarios = varIdusuarios;
       this.varNome = varNome;
       this.varApelido = varApelido;
       this.varCpf = varCpf;
       this.varDatanascimento = varDatanascimento;
       this.varSenha = varSenha;
       this.varNivel = varNivel;
       this.varAtivo = varAtivo;
       this.varVendases = varVendases;
    }
   
     @Id 

    
    @Column(name="var_idusuarios", unique=true, nullable=false)
    public int getVarIdusuarios() {
        return this.varIdusuarios;
    }
    
    public void setVarIdusuarios(int varIdusuarios) {
        this.varIdusuarios = varIdusuarios;
    }

    
    @Column(name="var_nome", length=100)
    public String getVarNome() {
        return this.varNome;
    }
    
    public void setVarNome(String varNome) {
        this.varNome = varNome;
    }

    
    @Column(name="var_apelido", length=50)
    public String getVarApelido() {
        return this.varApelido;
    }
    
    public void setVarApelido(String varApelido) {
        this.varApelido = varApelido;
    }

    
    @Column(name="var_cpf", length=14)
    public String getVarCpf() {
        return this.varCpf;
    }
    
    public void setVarCpf(String varCpf) {
        this.varCpf = varCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="var_datanascimento", length=10)
    public Date getVarDatanascimento() {
        return this.varDatanascimento;
    }
    
    public void setVarDatanascimento(Date varDatanascimento) {
        this.varDatanascimento = varDatanascimento;
    }

    
    @Column(name="var_senha", length=20)
    public String getVarSenha() {
        return this.varSenha;
    }
    
    public void setVarSenha(String varSenha) {
        this.varSenha = varSenha;
    }

    
    @Column(name="var_nivel")
    public Integer getVarNivel() {
        return this.varNivel;
    }
    
    public void setVarNivel(Integer varNivel) {
        this.varNivel = varNivel;
    }

    
    @Column(name="var_ativo", length=1)
    public String getVarAtivo() {
        return this.varAtivo;
    }
    
    public void setVarAtivo(String varAtivo) {
        this.varAtivo = varAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="varUsuarios")
    public Set getVarVendases() {
        return this.varVendases;
    }
    
    public void setVarVendases(Set varVendases) {
        this.varVendases = varVendases;
    }




}


