package bean;
// Generated 26/09/2025 08:58:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VarVendedores generated by hbm2java
 */
@Entity
@Table(name="var_vendedores"
    ,catalog="db_victoria_ruback"
)
public class VarVendedores  implements java.io.Serializable {


     private Integer varIdVendedor;
     private String varNome;
     private String varApelido;
     private String varCpf;
     private String varEmail;
     private Date varDataNascimento;
     private String varTelefone;
     private String varAtivo;

    public VarVendedores() {
    }

	
    public VarVendedores(String varNome) {
        this.varNome = varNome;
    }
    public VarVendedores(String varNome, String varApelido, String varCpf, String varEmail, Date varDataNascimento, String varTelefone, String varAtivo) {
       this.varNome = varNome;
       this.varApelido = varApelido;
       this.varCpf = varCpf;
       this.varEmail = varEmail;
       this.varDataNascimento = varDataNascimento;
       this.varTelefone = varTelefone;
       this.varAtivo = varAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="var_id_vendedor", unique=true, nullable=false)
    public Integer getVarIdVendedor() {
        return this.varIdVendedor;
    }
    
    public void setVarIdVendedor(Integer varIdVendedor) {
        this.varIdVendedor = varIdVendedor;
    }

    
    @Column(name="var_nome", nullable=false, length=100)
    public String getVarNome() {
        return this.varNome;
    }
    
    public void setVarNome(String varNome) {
        this.varNome = varNome;
    }

    
    @Column(name="var_apelido", length=100)
    public String getVarApelido() {
        return this.varApelido;
    }
    
    public void setVarApelido(String varApelido) {
        this.varApelido = varApelido;
    }

    
    @Column(name="var_cpf", length=14)
    public String getVarCpf() {
        return this.varCpf;
    }
    
    public void setVarCpf(String varCpf) {
        this.varCpf = varCpf;
    }

    
    @Column(name="var_email", length=100)
    public String getVarEmail() {
        return this.varEmail;
    }
    
    public void setVarEmail(String varEmail) {
        this.varEmail = varEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="var_data_nascimento", length=10)
    public Date getVarDataNascimento() {
        return this.varDataNascimento;
    }
    
    public void setVarDataNascimento(Date varDataNascimento) {
        this.varDataNascimento = varDataNascimento;
    }

    
    @Column(name="var_telefone", length=20)
    public String getVarTelefone() {
        return this.varTelefone;
    }
    
    public void setVarTelefone(String varTelefone) {
        this.varTelefone = varTelefone;
    }

    
    @Column(name="var_ativo", length=1)
    public String getVarAtivo() {
        return this.varAtivo;
    }
    
    public void setVarAtivo(String varAtivo) {
        this.varAtivo = varAtivo;
    }
    
    
    @Override
    public boolean equals(Object object) {
        if (object instanceof VarVendedores) {
            if (this.getVarIdVendedor()== ((VarVendedores) object).getVarIdVendedor()) {
                return true;
            }
        }

        return false;
    }





}


