package bean;
// Generated 26/09/2025 08:58:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VarVendas generated by hbm2java
 */
@Entity
@Table(name="var_vendas"
    ,catalog="db_victoria_ruback"
)
public class VarVendas  implements java.io.Serializable {


     private int varIdVendas;
     private VarClientes varClientes;
     private VarUsuarios varUsuarios;
     private Date varDataVendas;
     private BigDecimal varTotal;
     private Set varVendasBolsases = new HashSet(0);

    public VarVendas() {
    }

	
    public VarVendas(int varIdVendas) {
        this.varIdVendas = varIdVendas;
    }
    public VarVendas(int varIdVendas, VarClientes varClientes, VarUsuarios varUsuarios, Date varDataVendas, BigDecimal varTotal, Set varVendasBolsases) {
       this.varIdVendas = varIdVendas;
       this.varClientes = varClientes;
       this.varUsuarios = varUsuarios;
       this.varDataVendas = varDataVendas;
       this.varTotal = varTotal;
       this.varVendasBolsases = varVendasBolsases;
    }
   
     @Id 

    
    @Column(name="var_idVendas", unique=true, nullable=false)
    public int getVarIdVendas() {
        return this.varIdVendas;
    }
    
    public void setVarIdVendas(int varIdVendas) {
        this.varIdVendas = varIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="var_cliente")
    public VarClientes getVarClientes() {
        return this.varClientes;
    }
    
    public void setVarClientes(VarClientes varClientes) {
        this.varClientes = varClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="var_usuario")
    public VarUsuarios getVarUsuarios() {
        return this.varUsuarios;
    }
    
    public void setVarUsuarios(VarUsuarios varUsuarios) {
        this.varUsuarios = varUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="var_dataVendas", length=10)
    public Date getVarDataVendas() {
        return this.varDataVendas;
    }
    
    public void setVarDataVendas(Date varDataVendas) {
        this.varDataVendas = varDataVendas;
    }

    
    @Column(name="var_total", precision=10)
    public BigDecimal getVarTotal() {
        return this.varTotal;
    }
    
    public void setVarTotal(BigDecimal varTotal) {
        this.varTotal = varTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="varVendas")
    public Set getVarVendasBolsases() {
        return this.varVendasBolsases;
    }
    
    public void setVarVendasBolsases(Set varVendasBolsases) {
        this.varVendasBolsases = varVendasBolsases;
    }




}


