package bean;
// Generated 26/09/2025 08:58:21 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VarVendasBolsas generated by hbm2java
 */
@Entity
@Table(name="var_vendas_bolsas"
    ,catalog="db_victoria_ruback"
)
public class VarVendasBolsas  implements java.io.Serializable {


     private int varIdVendasBolsas;
     private VarBolsas varBolsas;
     private VarVendas varVendas;
     private Integer varQuantidade;
     private double varValorUnitario;

    public VarVendasBolsas() {
    }

	
    public VarVendasBolsas(int varIdVendasBolsas) {
        this.varIdVendasBolsas = varIdVendasBolsas;
    }
    public VarVendasBolsas(int varIdVendasBolsas, VarBolsas varBolsas, VarVendas varVendas, Integer varQuantidade, double varValorUnitario) {
       this.varIdVendasBolsas = varIdVendasBolsas;
       this.varBolsas = varBolsas;
       this.varVendas = varVendas;
       this.varQuantidade = varQuantidade;
       this.varValorUnitario = varValorUnitario;
    }
   
     @Id 

    
    @Column(name="var_idVendas_bolsas", unique=true, nullable=false)
    public int getVarIdVendasBolsas() {
        return this.varIdVendasBolsas;
    }
    
    public void setVarIdVendasBolsas(int varIdVendasBolsas) {
        this.varIdVendasBolsas = varIdVendasBolsas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="var_bolsas")
    public VarBolsas getVarBolsas() {
        return this.varBolsas;
    }
    
    public void setVarBolsas(VarBolsas varBolsas) {
        this.varBolsas = varBolsas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="var_vendas")
    public VarVendas getVarVendas() {
        return this.varVendas;
    }
    
    public void setVarVendas(VarVendas varVendas) {
        this.varVendas = varVendas;
    }

    
    @Column(name="var_quantidade")
    public Integer getVarQuantidade() {
        return this.varQuantidade;
    }
    
    public void setVarQuantidade(Integer varQuantidade) {
        this.varQuantidade = varQuantidade;
    }

    
    @Column(name="var_valor_unitario", precision=10)
    public double getVarValorUnitario() {
        return this.varValorUnitario;
    }
    
    public void setVarValorUnitario(double varValorUnitario) {
        this.varValorUnitario = varValorUnitario;
    }




}


